# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/30 * * * *'
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML requests
    - name: Run script
      run: python main.py
    - name: Commit files
      run: |
        git config --local user.email "bailiang9966@gmail.com"
        git config --local user.name "bailiang9966"
        git add -A
        git commit -m "Update Proxies (`date '+%F %H:%M %Z'`)" -a
        git branch -u origin/main
        
    - name: Push changes
      uses: ad-m/github-push-action@v0.7.0
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        branch: main
