# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/30 * * * *'
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML requests
    - name: Run script
      run: python main.py
    - name: Upload TXT file
      run: |
        git config --global user.name "bailiang9966"
        git config --global user.email "bailiang9966@gmail.com"
        git add all.txt
        git commit -m "Update all.txt on `date +'%Y-%m-%d %H:%M:%S'`"
        git push 