
on:
    push:
      branches: [ "main" ]
      paths-ignore:
        - 'out/**'
    pull_request:
      branches: [ "main" ]
      paths-ignore:
        - 'out/**'
    schedule:
      - cron: '0 * * * *'
permissions:
    contents: read
  
jobs:
    build:
  
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v4
        with:
            token: ${{ secrets.TOKEN_GITHUB }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
            python-version: "3.10"
      - name: Install dependencies
        run: |
            pip install requests
      - name: Run script
        run: python url_test.py

  
